# Generated by Django 5.0.14 on 2026-08-25 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=40)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under review'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='reported', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('media_url', models.URLField()),
                ('public_id', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.incident')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('reported', 'Reported'), ('under_review', 'Under review'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under review'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_status_changes', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app.incident')),
            ],
            options={
                'ordering': ('-changed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['user', '-created_at'], name='app_inciden_user_id_323624_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', '-created_at'], name='app_inciden_status_72d3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['type'], name='app_inciden_type_605bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['location_lat', 'location_lng'], name='app_inciden_locatio_c38e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentmedia',
            index=models.Index(fields=['incident'], name='app_inciden_inciden_687d90_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentstatushistory',
            index=models.Index(fields=['incident', '-changed_at'], name='app_inciden_inciden_ef782e_idx'),
        ),
    ]
